project:
  type: website

website:
  title: "Students-psychology"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Data analysis.qmd
        text: Data analysis
      - about.qmd
      - href: Sources.qmd
        text: Sources
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



